# Generated by Django 4.0.5 on 2022-06-11 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=255)),
                ('link', models.URLField(validators=[django.core.validators.URLValidator(regex='^(http|https)://', schemes=['http', 'https'])])),
                ('fecha_creada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
