# Generated by Django 4.0.5 on 2022-06-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='is_dafault',
            field=models.BooleanField(default=False),
        ),
    ]
