# Generated by Django 4.0.5 on 2022-06-14 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0003_foto_is_dafault'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='is_dafault',
        ),
    ]
