# Generated by Django 4.0.5 on 2022-06-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0004_remove_foto_is_dafault'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
